# Generated by Django 2.1.7 on 2019-03-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatColorsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.TextField(blank=True, null=True, unique=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cat_colors_info',
            },
        ),
        migrations.CreateModel(
            name='Cats',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('color', models.TextField(blank=True, null=True)),
                ('tail_length', models.IntegerField(blank=True, null=True)),
                ('whiskers_length', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cats',
            },
        ),
        migrations.CreateModel(
            name='CatsStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_length_mean', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('tail_length_median', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('tail_length_mode', models.TextField(blank=True, null=True)),
                ('whiskers_length_mean', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('whiskers_length_median', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('whiskers_length_mode', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cats_stat',
            },
        ),
    ]
